#! /bin/bash

# Install packages

sudo xbps-install -Su
sudo xbps-install -S $(cat INSTALL/repos)
sudo xbps-install -S $(cat INSTALL/base)
sudo xbps-install -S $(cat INSTALL/drivers)
sudo xbps-install -S $(cat INSTALL/desktop)
sudo xbps-install -S $(cat INSTALL/media)
sudo xbps-install -S $(cat INSTALL/progs)
sudo xbps-install -S $(cat INSTALL/game)

# Install services

sudo ln -s /etc/sv/dbus /var/service
sudo ln -s /etc/sv/lightdm /var/service
sudo ln -s /etc/sv/acpid /var/service
#sudo ln -s /etc/sv/dbus /var/service
#sudo ln -s /etc/sv/dbus /var/service
modprobe kvm-amd
sudo usermod --shell /bin/fish zen

# creating bare repository
mkdir .void
cd .void
git init --bare
